<html><header><title>Exceptions in Validationrules</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Exceptions in Validationrules</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/2792.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>eDjinn posted on Friday, April 27, 2007</h2>I would like to suggest a change in the exception handling of the validation rules.<br>When an exception occurs, it is quite difficult to find which validation is responsable for this error.<br><br>When a try-catch is added to the function<br><font color="#0000ff"><b>private void</b></font> Csla.Validation<font color="#deb887">.</font><font color="#deb887"><font color="#0000ff">ValidationRules</font>.</font>CheckRules(<font color="#0000ff">List&lt;IRuleMethod&gt;</font> list)<br><br>CSLA can provide us with more detailed information, like:<br><br><font color="#0000ff"><b>catch</b></font> ( Exception <b><font color="#ff0000">_ex </font></b>)&nbsp;&nbsp;&nbsp;&nbsp; <font color="#008000"><i>//Got conversion exception Int/String</i></font><br>{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#0000ff"> throw new</font></b> Exception( <b><font color="#0000ff">string</font></b>.Format( <font color="#a52a2a"><b>"Exception in {0} {1}"</b></font>, list[index].GetType().Name, list[index].RuleName ), <b><font color="#ff0000">_ex</font></b> );<br>} <br><br>Depending on the exception Type, the exception might not be thrown, but instead the rule can be broken. <br><br>An exception occurred when I binded a StringMaxLenth rule on an int field. I had quite a hard time finding the field in question. <br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Friday, April 27, 2007</h2>Good idea, I've added it to the <A href="http://www.lhotka.net/Article.aspx?id=42066ed8-ea65-44a3-b7fd-035c9d8bfa36">wish list</A>.</div><div style='padding:0 15 3 15;background-color:powderblue'><h2>david.wendelken replied on Tuesday, May 01, 2007</h2>What section of code did you put the try block on?</div><div style='padding:0 15 3 15;background-color:powderblue'><h2>eDjinn replied on Wednesday, May 02, 2007</h2>Though I'm quite new to the CSLA concept (and C# for that matter), there are the changes i placed in the CSLA code: <br><ul><li>in the file "BusinessBase.cs" (csla20cs\Csla\) I changed the function Clone() to virual (public abstract class BusinessBase&lt;T&gt; -- line 100)</li><li>in the file "ValidationRules.cs" (csla20cs\Csla\Validation\) I changed the function [Csla.Validation].ValidationRules.CheckRules() and .CheckRules(List&lt;IRuleMethod&gt; list), placing try-catch around the complete functions. <br></li></ul>In this last function (<i><b>private void</b> CheckRules(List&lt;IRuleMethod&gt; list)</i>), you can place a try-catch in the <i>for-loop</i>: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; for ( int index = 0; index &lt; list.Count; index++ )<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {...}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch ( Exception _ex ){<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; System.Diagnostics.Trace.WriteLine(...);<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; throw new Exception( string.Format( "Exception in {0} {1}", <br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; list[index].GetType().Name, list[index].RuleName ), _ex );<br>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }<br><br>I use CodeSmith to generate my CSLA-classes, but next to these default functions, properties and variables, I override the functions <br><ul><li><i><b>public virtual bool IsValid</b></i> of <i><b>public abstract class BusinessBase.</b></i></li><li><i><b>public virtual T Save()</b></i> of <b><i>public abstract class BusinessBase&lt;T&gt;.</i></b><br></li></ul>In some cases, the IsValid function does not check all the rules again, resulting a false NotValid state. Using the override, I can check the rules manually. <br><br>I hope this helps...<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>david.wendelken replied on Wednesday, May 02, 2007</h2><P>Thanks!&nbsp; </P>
<P>&nbsp;</P>
<P>&nbsp;</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Wednesday, May 02, 2007</h2><P>It may be worth noting that Clone() is already virtual in that there's a virtual/Overridable method called GetClone() that actually does all the work. If you want to alter the behavior of Clone() all you need to do is override GetClone(). (in version 2.1+)</P>
<P>Providing better exception detail for rule methods that generate exceptions is in the wish list, and may yet make it into 3.0 depending on time.</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Wednesday, May 02, 2007</h2><P>OK, I'm looking seriously at this now, and this is an interesting issue - in particular, whether to throw a more detailed exception (that might be hard to find behind data binding), or to convert any exception into a broken rule.</P>
<P>I do wonder if it wouldn't be better to convert any exception into a broken rule - but to alter the rule's description text to reflect the details of the exception. The broken rule description would end up reading (in English) something like:</P>
<P><EM>Validation rule xyz failed in property abc (&lt;original exception message here&gt;)</EM></P>
<P>The advantage to this is that it would work nicely in Windows Forms and WPF, where exceptions are otherwise often silently captured by data binding, and can therefore be hard to find/fix.</P>
<P>The disadvantage to this is that you lose the stack trace and other exception detail.</P>
<P>The thing is, that even in cases where data binding does capture and <EM>display</EM> the exception, they only display the Message property in the tooltip. So in that case it is a wash as to whether I break the rule or throw an exception, because the tooltip would be better either way.</P>
<P>But in the cases where data binding just eats the exception, breaking the rule would produce a better result.</P>
<P>But <EM>then</EM> there's the ValidationRules.CheckRules() case, where data binding isn't even involved, and a good argument can be made that throwing an exception makes for the easiest debugging.</P>
<P>So I'm open to suggestions one way or the other here. Throw a more detailed exception? Or break the rule and override the Description with the exception details?</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>david.wendelken replied on Wednesday, May 02, 2007</h2><BLOCKQUOTE><div><img src="/Themes/default/images/icon-quote.gif"> <strong>RockfordLhotka:</strong></div><div>
<P><EM>Validation rule xyz failed in property abc (&lt;original exception message here&gt;)</EM></P>
<P></div></BLOCKQUOTE></P>
<P>That's a useful message format!</P>
<P><BLOCKQUOTE><div><img src="/Themes/default/images/icon-quote.gif"> <strong>RockfordLhotka:</strong></div><div></P>
<P>So I'm open to suggestions one way or the other here. Throw a more detailed exception? Or break the rule and override the Description with the exception details?</P>
<P></div></BLOCKQUOTE></P>
<P>Maybe you should do both, and either let context decide, or provide a configuration option for the developer to choose from?</P>
<P>While you're looking at refactoring the rules handling, take a look at this thread. Thanks!</P>
<P><A HREF="/forums/thread/14396.aspx">http://forums.lhotka.net/forums/thread/14396.aspx</A></P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>eDjinn replied on Wednesday, May 02, 2007</h2>I see the problem with Exception or BrokenRules. <br>What I see in my own code is an Exception on a default rule MaxStringLength there the object is an int type, not a string. The Exception reads something like (translated from dutch): Cannot implicitly convert from int to string. <br>Because I was filling the BusinessListBase descendent directly, assigning field values directly in the BusinessBase descendent, I got this exception when I tried to <i>BusinessListBase.Save()</i><br><br>For this reason, it doesn't mather to me much if it will be an exception or a broken rule. It would be nice if I could see in the catch or in the brokenrules collection what rule on what field/property of what record (<i>protected override object BusinessBase.GetIdValue()</i>) the problem occurs. <br><br>If the sollution is either Exception or Brokenrule, one should handle it. <br><br>What I meant with the Exception type, in case of a conversion Exception, it is obviously an error caused by the programmer. Then, it would be best to keep it as an Exception (easier debugging). <br>It it's a problem caused by a user, it would be better if it would be a broken rule (not loose anything the user typed). <br><br>I'm not sure it the latter is even possible (that is, if it's possible to get an exception if the programmer did not make a mistake creating/assigning rules).<br><br>Hope this helps...<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Wednesday, May 02, 2007</h2><P>You have a good point - an unhandled exception from a rule method should be a developer issue, not a user issue. In other words, a developer really shouldn't allow unhandled exceptions to occur in a rule method, so this issue should occur during development and testing, not really at runtime.</P>
<P>Regardless, it should be easy for the developer to use the resulting detail. There are various scenarios:</P>
<OL>
<LI>PropertyHasChanged is called in a web app, web service, WCF service or workflow 
<LI>PropertyHasChanged is called in a Windows app with data binding 
<LI>PropertyHasChanged is called in a Windows app without data binding 
<LI>PropertyHasChanged is called in a WPF app with data binding 
<LI>PropertyHasChanged is called in a WPF app without data binding 
<LI>ValidationRules.CheckRules is called</LI></OL>
<P>In 1, 3, 5 and 6 throwing a detailed exception works great. In all these cases the developer (typically the UI developer) would get the exception directly and would see the full details of the issue.</P>
<P>In 2 <EM>sometimes</EM> the exception would appear, but other times data binding eats the exception. In this case the broken rule solution may be superior.</P>
<P>In 4 either approach is technically workable. The UI developer can write their XAML such that they see a broken rule (using csla:ValidationPanel and appropriate UI styling), or an exception (using the WPF exception control and appropriate UI styling).</P>
<P>Hmm. Putting it like this is useful, because <EM>only</EM> 2 has an issue with the exception approach, and then only sometimes. So clearly the exception approach offers the best solution to the widest range of scenarios.</P></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
