<html><header><title>IsDirty: base.IsDirty vs. this.IsDirty</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>IsDirty: base.IsDirty vs. this.IsDirty</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/7418.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>MadGerbil posted on Friday, August 07, 2009</h2>I know a developer who wrote the following code:<br /><br />protected override void DataPortal_Update()<br />{<br />     if(base.IsDirty)<br />     {<br />          //do stuff<br />     }<br />}<br /><br />public override bool IsDirty<br />{<br />     get<br />     {<br />          return base.IsDirty || _childCollection.IsDirty<br />     }<br />}<br /><br />When stepping through the code in the DataPortal_Update the base.IsDirty will show a value of 'true' but still skips the code contained in the if statement.<br /><br />This tells me some type of error is being generated - I tried to try/catch the error but couldn't do it.<br /><br />The way to correct the problem is to change the code in the DataPortal_Update from 'base.IsDirty' to 'this.IsDirty'.<br /><br />The reason for this post is I want to understand WHY base.IsDirty is wrong and this.IsDirty is correct.   </div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Friday, August 07, 2009</h2><P>I don't know - that sounds very odd. If it were generating an exception it would exit the method right away, not just skip that block.</P>
<P>Are you sure base.IsDirty is returning true? Maybe the object hasn't changed, and only some child object has changed? (that'd make base.IsDirty different from this.IsDirty)</P></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
