<html><header><title>CSLA 3.8.2 Tests</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>CSLA 3.8.2 Tests</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/8634.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>Smith866 posted on Tuesday, March 09, 2010</h2><p>I was wondering if anybody else was having issues getting all of the unit tests for CSLA 3.8.2 to pass?&nbsp; I am able to get all of the 3.8.1 tests to pass, but the following 2 tests always fail in 3.8.2 (and 3.8.3 beta):</p>
<p>Csla.Test.Data.ContextTests.Using_TransactionManager_Insert_2records_increases_count_by2_then_removing_them_decreases_count_by2:<br />Csla.DataPortalException : DataPortal.Update failed (System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.<br />&nbsp;&nbsp; at System.Data.SqlClient.SqlTransaction.ZombieCheck()<br />&nbsp;&nbsp; at System.Data.SqlClient.SqlTransaction.Rollback()<br />&nbsp;&nbsp; at Csla.Data.TransactionManager`2.DeRef() in C:\Code\cslacs-3.8.2-100201\cslacs\Csla\Data\TransactionManager.cs:line 211<br />&nbsp;&nbsp; at Csla.Data.TransactionManager`2.Dispose() in C:\Code\cslacs-3.8.2-100201\cslacs\Csla\Data\TransactionManager.cs:line 232<br />&nbsp;&nbsp; at Csla.Test.Data.TransactionContextUserList.DataPortal_Update() in C:\Code\cslacs-3.8.2-100201\cslatest\Csla.Test\Data\TransactionContextUserList.cs:line 59<br />&nbsp;&nbsp; at dm(Object , Object[] )<br />&nbsp;&nbsp; at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Object[] parameters) in C:\Code\cslacs-3.8.2-100201\cslacs\Csla\Reflection\MethodCaller.cs:line 357)<br />&nbsp; ----&gt; Csla.Reflection.CallMethodException : DataPortal_Update method call failed<br />&nbsp; ----&gt; System.InvalidOperationException : This SqlTransaction has completed; it is no longer usable.</p>
<p>&nbsp;</p>
<p>AND</p>
<p>&nbsp;</p>
<p>Csla.Test.Data.ContextTests.Using_TransactionManager_Insert_of_2records_rolls_back_if_second_record_fails_insert:<br />&nbsp; Transaction context should have been null<br />&nbsp; Expected: 0<br />&nbsp; But was:&nbsp; 1</p>
<p>I am using SQL Server 2008 SP1.&nbsp; I have tried moving between Express and Developer editions, with the same result from either.</p>
<p>I apologize if I have missed something obvious, I am new to CSLA.</p></div><div style='padding:0 15 3 15;background-color:lightgreen'><h2>RockfordLhotka replied on Tuesday, March 09, 2010</h2><p>There&#39;s clearly a problem with those tests, I agree. I don&#39;t know that I&#39;ll trace down the issue in 3.8 anymore, but the problem is there in 4 as well, and will certainly be addressed.</p>
<p>I strongly suspect the tests are broken. A change was made to TransactionManager in 3.8.2, and I think the tests were not updated accordingly.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
